name: containerization 
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build and Scan CVE
      run: docker build -t r-app-cve-scan .

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: ./sbom.json