name: containerization 
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
# You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
          
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build and Scan CVE
      run: docker build -t r-app-cve-scan .

    - name: Tag Docker Image
      run: docker tag r-app-cve-scan r-app-cve-scan:latest
      
    - name: Generate SBOM with Syft
      run: docker run --rm -v ${{github.workspace}}:/src anchore/syft /src -o json > sbom.json
       

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: ./sbom.json